spring:
  redis:
    client-type: jedis
    host: 110.42.162.30
  datasource:
    username: admin
    password: 1234
    url: jdbc:mysql://localhost:3306/BankSystem
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
  mvc:
    hiddenmethod:
      filter:
        enabled: true
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
logging:
  level:
    com.cx.bank: debug

